config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/home', to: 'posts#index'

     resources :posts
     resources :users
     
     get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
    
    before_save {self.email=email.downcase}
    validates :name, presence: true, length: {minimum:3, maximum:40} 
    VALID_EMAIL_REGEX = /\A[\w+\-,]+@[a-z\d\-,]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:105}, 
                                          uniqueness: { case_sensitive: false }, 
                                          format: { with: VALID_EMAIL_REGEX }
    has_secure_password    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :featured_post
  
  def featured_post
    @featured_post = Post.order("RANDOM()").first
  end
  
  def current_user
    @current_user ||= User.find( session[:user_id] ) if session[:user_id]
  end
  
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You have to be logged in in order to do this."
      redirect_to root_path
    end
  end
  
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    
    def new
        
    end
    
    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            flash[:success] = "You are logged in."
            redirect_to root_path
        else
            flash.now[:danger]= "Your email and password doesn`t match"
            render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:success] = "You are logged out."
        redirect_to root_path
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
    before_action :require_user, only: [:new]
      
    def index
        @posts = Post.all.paginate(page: params[:page], per_page: 10).order("created_at desc")
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            flash[:success] = "The post is successfully created"
            redirect_to posts_path
        else
            render :new
        end
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :description, :user_id, :created_at, :updated_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          flash[:success]="The profile is successfully created. You can log in with your username and password."
          redirect_to root_path
        else
          render :new
        end
    end
    
    def show
      @user = User.find(params[:id])
    end
    
    private
      def user_params
        params.require(:user).permit(:name, :email, :password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-md-12">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"> <%= message %>
            <a class="close" data-dismiss="alert"> &#215; </a>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">  
  <div class="container-fluid"> 
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> 
      <%= link_to "Blog", root_path,  id: "logo" %> 
    </div> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6"> 
      <ul class="nav nav-pills">
    <li><%= link_to "Posts", posts_path %></li>
    
    
    </div> 
    
    <% if logged_in? %>
      <li role="presentation" class="dropdown pull-right">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="fixed">
          <%= current_user.name %> <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Create new post", new_post_path %></li> &nbsp;
          <li role="presentation"><%= link_to "Sign out", logout_path %></li>
    <% else %>
      <% if session[:user_id].nil? %>
        <li role="presentation" class= "pull-right"><%= link_to "Sign in", login_path %> </li>
        <li role="presentation" class= "pull-right"><%= link_to "Sign up", new_user_path %> </li>
      <% end %>
    <% end %>
    
  </div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Log in' %>

<div class="row">
  <div class="well col-md-6 col-md-offset-3">
    <%= form_tag '/login' do %>
      <%= label_tag :email %>
      <%= text_field_tag :email %>
              
      <%= label_tag :password %>
      <%= password_field_tag :password %>
              
      <%= submit_tag 'Log in', class: 'btn btn-success' %>
        
    <% end %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="cener jumbotron" id="divToChange">
    <h3>Featured post:</h3>
    <h2><%= link_to featured_post.title , post_path(featured_post.id) %></h2>
</div>
<%= will_paginate %>
<% @posts.each do |p| %>
    <div class="panel panel-default">
        <div class="panel-heading"><%= link_to p.title , post_path(p.id) %></div>
        <div class="panel-body">
            <p><%= p.description %></p>
            </br>
            <h6>Post added by: <%= link_to p.user.name , user_path(p.user.id) %></h6>
        </div>
    </div>
<% end %>
<%= will_paginate %>

app/views/posts/new.html.erb
<%= render 'shared/page_title', title: "Create new post" %> 
<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @post do |f| %>
        <%= f.label :"Title of the post" %>
        <%= f.text_field :title, :size => "40" %>
        </br></br>
        <%= f.label :"Description of the post" %>
        <%= f.text_field :description, :size => "40" %>
        </br></br>
        <%= f.submit 'Create Post', class: "btn btn-success pull-right" %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<%= render 'shared/page_title', title: "Post" %>
<div class="col-lg-12 well">
        <strong> <h3><%= @post.title %></h3> </strong>
        <h4><%= @post.description %></h4>
        <h6><u>This post was created by:</u> <%= @post.user.name %> </h4>
</div>
        
        
        
    

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="alert alert-danger col-md-8 col-md-offset-2">
            <h5>Something is wrong:</h5>
            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li> <%= msg %> </li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/shared/_page_title.html.erb
    <h1><%= title %></h1>
    <hr/>

app/views/users/new.html.erb
<%= render 'shared/page_title', title: "Sign Up!" %> 
<%= render 'shared/errors', obj: @user %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @user do |f| %>
        <%= f.label :Name %>
        <%= f.text_field :name %></br>
        </br></br>
        <%= f.label :email %>
        <%= f.text_field :email %></br>
        </br></br>
        <%= f.label :Password %>
        <%= f.password_field :password %></br>
        </br></br>
        <%= f.submit 'Sign up', class: "btn btn-success pull-right" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/page_title', title: "User" %>
<div class="col-lg-12 well">
        <strong> <h3> Username: <%= @user.name %></h3> </strong>
        <h4>Email of the user: <%= @user.email %></h4>
</div>
        